### ISSUE TITLE
Unifi Voucher Not Created, Will Not Print

### ISSUE THREAD

**Issue by Kniteschaed** [PaintSplasher/unifi-voucher-service#1]
Issues
- Voucher code not created in Unifi
- Brother QL-700 does not print via terminal or through php page

Equipment
- Raspberry Pi 3 B+ (B Plus)
- Official 7" Touchscreen
- Brother QL-700
- Unifi Controller v5.6.26

Setup & Testing
- I have followed the instructions.
- I have disabled "editor lite" mode on the QL-700
- I can print a test label from the Brother interface (http://localhost:8013)
- "sudo brother_ql_print /home/pi/Desktop/printfile.bin /dev/usb/lp0" will not print a label
--INFO: brother_ql.backends.helpers:Sending instructions to the printer. Total: 40172 bytes.
--WARNING: brother_ql.backends.helpers:'printing completed' status not received
--WARNING: brother_ql.backends.helpers:'waiting to receive' status not received.
--WARNING: brother_ql.backends.helpers:Printing potentially not successful?
- Unifi Voucher Service page does not generate a voucher code in Unifi and will not print a label - just shows "PRINTING...", dims the other buttons, and never changes back (also no way to cancel or escape this screen without killing the webpage from task manager).

Pictures
![service print](https://user-images.githubusercontent.com/32316315/46548260-5d83f480-c883-11e8-9176-8fe86b39f742.jpg)
![terminal print](https://user-images.githubusercontent.com/32316315/46548261-5e1c8b00-c883-11e8-8557-9bb8bb529850.jpg)

**Comment by PaintSplasher** [comment]
Through some deprecated drivers and codelines, please try the new branch v2.0 what is released some hours ago and tell me if something goes wrong. Thank you.
