### ISSUE TITLE
Unable to print QL-800 web stuck on print

### ISSUE THREAD

**Issue by nmlpg12** [PaintSplasher/unifi-voucher-service#10]
Hello for some reason i made the changes ql-800 and lsusb id 
for some reason its just stuck on printing i need help

**Comment by PaintSplasher** [comment]
Can you please give us some details on what you exactly changed, did you checked your lsusb id twice? Are you on a testprint or did you the rest of the steps?

**Comment by nmlpg12** [comment]
1 yea i did the test print and added the --red while test script and it worked. the only part that i haven't don is the unclutter but i didn't want to do it until i tested that it worked. when i added the UniFi setting i created special account for the printer that only has access to the specific site. i named san andress i suspect its that because the script doesn't send the print command because i don't get an error on the printer either

**Comment by nmlpg12** [comment]
![D67EB407-8550-480D-B7E4-AE5C2097C95F](https://user-images.githubusercontent.com/61538216/75470718-b8295f00-5956-11ea-812d-3bc77b591127.jpeg)
![12AA1A16-2CD8-49E1-95E4-5498056BB3E5](https://user-images.githubusercontent.com/61538216/75470722-ba8bb900-5956-11ea-9a7f-27760334d0fd.jpeg)
![798B8E2D-1713-42EE-BE59-9C9E95C63A7E](https://user-images.githubusercontent.com/61538216/75470727-bb244f80-5956-11ea-8946-52fd31abe880.jpeg)
![FEFFACCA-F75D-4A29-AFE8-160A91A3291D](https://user-images.githubusercontent.com/61538216/75470730-bc557c80-5956-11ea-8bd5-918d406efd81.jpeg)
![A1890C27-4440-41FF-9FC3-B2D144C2879D](https://user-images.githubusercontent.com/61538216/75470736-bd86a980-5956-11ea-9283-6226dfbf179b.jpeg)
![C0016BCD-7CEB-438D-BFE9-D93F7571E2C6](https://user-images.githubusercontent.com/61538216/75470741-be1f4000-5956-11ea-968c-27a8753d16a0.jpeg)
![BA517456-4503-4BAE-BC54-29ABC9911C27](https://user-images.githubusercontent.com/61538216/75470745-bf506d00-5956-11ea-84e3-6170bd34cea5.jpeg)
![Uploading 220DD3D8-4115-4E75-AE97-5BC83771A252.jpeg…]()

**Comment by nmlpg12** [comment]
![0806A115-3AC0-4F7A-B637-E000D86E115A](https://user-images.githubusercontent.com/61538216/75470985-25d58b00-5957-11ea-9b4b-972ac72b758f.jpeg)
![C1ED6498-1546-46E4-9188-3F8122629241](https://user-images.githubusercontent.com/61538216/75470987-279f4e80-5957-11ea-9326-5858f46c82c4.jpeg)
![94CE012F-5248-4124-9060-D1D7CAA8D348](https://user-images.githubusercontent.com/61538216/75470992-28d07b80-5957-11ea-885a-7fe5708144b0.jpeg)
![72462501-7746-4409-80A5-F5175F847C01](https://user-images.githubusercontent.com/61538216/75470995-2a01a880-5957-11ea-9974-a6b87174672e.jpeg)
![088DBCB0-8974-412D-80C1-02808AF6A1CD](https://user-images.githubusercontent.com/61538216/75470999-2b32d580-5957-11ea-8452-51836abda2d5.jpeg)
![ADB515F3-DFF7-4DF1-BB1D-26115A007D40](https://user-images.githubusercontent.com/61538216/75471001-2c640280-5957-11ea-9005-c6b1dae31dae.jpeg)
![2447F9DB-DB38-4115-AA03-FAC348AFB7E6](https://user-images.githubusercontent.com/61538216/75471002-2d952f80-5957-11ea-90a5-f597963259c3.jpeg)

**Comment by nmlpg12** [comment]
![image](https://user-images.githubusercontent.com/61538216/75475299-2c1b3580-595e-11ea-9306-20ac9b441c89.jpg)

It hangs there doesn’t do anything 
Noticed that my controller https certificate needs renewing

**Comment by nmlpg12** [comment]
where can i see the error logs
?

**Comment by nmlpg12** [comment]
[Thu Feb 27 20:20:09.727098 2020] [mpm_prefork:notice] [pid 704] AH00169: caught SIGTERM, shutting down
[Thu Feb 27 20:20:41.875610 2020] [mpm_prefork:notice] [pid 670] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Thu Feb 27 20:20:41.877824 2020] [core:notice] [pid 670] AH00094: Command line: '/usr/sbin/apache2'
[Thu Feb 27 20:24:16.270961 2020] [php7:error] [pid 725] [client ::1:41774] PHP Parse error:  syntax error, unexpected '"/var/www/html/"' (T_CONSTANT_ENCAPSED_STRING), expecting '[' in /var/www/html/unifi-voucher-service/codes/1-day-free.php on line 31, referer: http://localhost/unifi-voucher-service/index.php
[Thu Feb 27 20:26:21.179602 2020] [php7:error] [pid 1936] [client ::1:41794] PHP Parse error:  syntax error, unexpected '"/var/www/html/"' (T_CONSTANT_ENCAPSED_STRING), expecting '[' in /var/www/html/unifi-voucher-service/codes/1-day-free.php on line 31, referer: http://localhost/unifi-voucher-service/index.php
[Thu Feb 27 20:27:15.059468 2020] [mpm_prefork:notice] [pid 670] AH00169: caught SIGTERM, shutting down
[Thu Feb 27 20:27:45.340203 2020] [mpm_prefork:notice] [pid 676] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Thu Feb 27 20:27:45.356083 2020] [core:notice] [pid 676] AH00094: Command line: '/usr/sbin/apache2'
[Thu Feb 27 20:31:44.825808 2020] [php7:error] [pid 729] [client ::1:46946] PHP Parse error:  syntax error, unexpected '"/var/www/html/"' (T_CONSTANT_ENCAPSED_STRING), expecting '[' in /var/www/html/unifi-voucher-service/codes/1-day-free.php on line 31, referer: http://localhost/unifi-voucher-service/index.php
[Thu Feb 27 20:31:51.496085 2020] [php7:warn] [pid 731] [client ::1:46948] PHP Warning:  require_once(/usr/src/UniFi-API-client/src/Client.php): failed to open stream: No such file or directory in /var/www/html/unifi-voucher-service/codes/1-day-fastpass.php on line 13, referer: http://localhost/unifi-voucher-service/index.php
[Thu Feb 27 20:31:51.496316 2020] [php7:error] [pid 731] [client ::1:46948] PHP Fatal error:  require_once(): Failed opening required '/usr/src/UniFi-API-client/src/Client.php' (include_path='.:/usr/share/php') in /var/www/html/unifi-voucher-service/codes/1-day-fastpass.php on line 13, referer: http://localhost/unifi-voucher-service/index.php
[Thu Feb 27 20:32:37.985894 2020] [mpm_prefork:notice] [pid 676] AH00169: caught SIGTERM, shutting down
[Thu Feb 27 20:33:06.844586 2020] [mpm_prefork:notice] [pid 675] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Thu Feb 27 20:33:06.853293 2020] [core:notice] [pid 675] AH00094: Command line: '/usr/sbin/apache2'
[Thu Feb 27 20:34:15.267785 2020] [php7:error] [pid 728] [client ::1:56716] PHP Parse error:  syntax error, unexpected '"/var/www/html/"' (T_CONSTANT_ENCAPSED_STRING), expecting '[' in /var/www/html/unifi-voucher-service/codes/1-day-free.php on line 31, referer: http://localhost/unifi-voucher-service/index.php
[Thu Feb 27 20:35:10.477026 2020] [php7:warn] [pid 729] [client ::1:56728] PHP Warning:  require_once(/usr/src/UniFi-API-client/src/Client.php): failed to open stream: No such file or directory in /var/www/html/unifi-voucher-service/codes/1-day-fastpass.php on line 13, referer: http://localhost/unifi-voucher-service/index.php
[Thu Feb 27 20:35:10.477260 2020] [php7:error] [pid 729] [client ::1:56728] PHP Fatal error:  require_once(): Failed opening required '/usr/src/UniFi-API-client/src/Client.php' (include_path='.:/usr/share/php') in /var/www/html/unifi-voucher-service/codes/1-day-fastpass.php on line 13, referer: http://localhost/unifi-voucher-service/index.php
[Thu Feb 27 20:36:11.996940 2020] [php7:warn] [pid 730] [client ::1:56746] PHP Warning:  require_once(/usr/src/UniFi-API-client/src/Client.php): failed to open stream: No such file or directory in /var/www/html/unifi-voucher-service/codes/1-month-free.php on line 13, referer: http://localhost/unifi-voucher-service/index.php
[Thu Feb 27 20:36:11.997300 2020] [php7:error] [pid 730] [client ::1:56746] PHP Fatal error:  require_once(): Failed opening required '/usr/src/UniFi-API-client/src/Client.php' (include_path='.:/usr/share/php') in /var/www/html/unifi-voucher-service/codes/1-month-free.php on line 13, referer: http://localhost/unifi-voucher-service/index.php
[Thu Feb 27 20:43:25.164956 2020] [php7:error] [pid 734] [client ::1:56760] PHP Parse error:  syntax error, unexpected '"/var/www/html/"' (T_CONSTANT_ENCAPSED_STRING), expecting '[' in /var/www/html/unifi-voucher-service/codes/1-day-free.php on line 31, referer: http://localhost/unifi-voucher-service/index.php
                                                                                                        [Thu Feb 27 21:17:40.631704 2020] [mpm_prefork:notice] [pid 573] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Thu Feb 27 21:17:40.638646 2020] [core:notice] [pid 573] AH00094: Command line: '/usr/sbin/apache2'
[Thu Feb 27 21:17:28.121339 2020] [mpm_prefork:notice] [pid 666] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Thu Feb 27 21:17:28.123761 2020] [core:notice] [pid 666] AH00094: Command line: '/usr/sbin/apache2'
[Thu Feb 27 21:38:02.082940 2020] [php7:error] [pid 720] [client ::1:53988] PHP Parse error:  syntax error, unexpected '"/var/www/html/"' (T_CONSTANT_ENCAPSED_STRING), expecting '[' in /var/www/html/unifi-voucher-service/codes/1-day-free.php on line 31, referer: http://localhost/unifi-voucher-service/index.php
[Thu Feb 27 21:41:10.268518 2020] [mpm_prefork:notice] [pid 666] AH00169: caught SIGTERM, shutting down
[Thu Feb 27 21:41:34.561463 2020] [mpm_prefork:notice] [pid 722] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Thu Feb 27 21:41:34.574888 2020] [core:notice] [pid 722] AH00094: Command line: '/usr/sbin/apache2'

**Comment by PaintSplasher** [comment]
You must have missed a step, your apache can't find the correct files "No such file or directory" and because of "PHP Parse error: syntax error, unexpected" on 31 you maybay edited a file you shouldn't have to edit. Or you changed the uvs_folder name or added a wrong character to it.

**Comment by nmlpg12** [comment]
*   Trying 149.28.49.108...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x6346f8)
* Connected to wifi.haciendasanandres.mx (149.28.49.108) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=wifi.haciendasanandres.mx
*  start date: Dec 29 22:00:47 2019 GMT
*  expire date: Mar 28 22:00:47 2020 GMT
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> POST /api/s/default/cmd/hotspot HTTP/1.1
Host: wifi.haciendasanandres.mx:8443
Accept: */*
Cookie: unifises=4lW3sxWGu5OtMZAmNu3sW5Wp5yjZ1PD8;csrf_token=qRW2Yrj7RmiA8YhKwaWjqux923eUiCPo
Content-Type: application/json;charset=UTF-8
Content-Length: 93

* upload completely sent off: 93 out of 93 bytes
< HTTP/1.1 401 
< vary: Origin
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
< X-Frame-Options: DENY
< Content-Type: application/json;charset=UTF-8
< Content-Length: 63
< Date: Thu, 27 Feb 2020 23:00:35 GMT
< 
* Connection #0 to host wifi.haciendasanandres.mx left intact
* Expire in 0 ms for 6 (transfer 0x6346f8)
* Expire in 10000 ms for 2 (transfer 0x6346f8)

**Comment by nmlpg12** [comment]
i fixed that problem it wasn't a file that i shouldn't have edited it was a problem where a the UniFi-API-service folder had one lowercase letter UniFi

**Comment by nmlpg12** [comment]
* Expire in 1 ms for 1 (transfer 0[Thu Feb 27 23:12:00.641250 2020] [php7:notice] [pid 2449] [client ::1:47168] cURL debug: needed to reconnect to UniFi controller, referer: http://localhost/unifi-voucher-service/index.php
x634b60)
* Expire in 2 ms for 1 (transfer 0x634b60)
* Expire in 1 ms for 1 (transfer 0x634b60)
* Expire in 1 ms for 1 (transfer 0x634b60)
* Expire in 1 ms for 1 (transfer 0x634b60)
*   Trying 149.28.49.108...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x634b60)
* Connected to wifi.haciendasanandres.mx (149.28.49.108) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=wifi.haciendasanandres.mx
*  start date: Dec 29 22:00:47 2019 GMT
*  expire date: Mar 28 22:00:47 2020 GMT
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> POST /api/s/default/cmd/hotspot HTTP/1.1
Host: wifi.haciendasanandres.mx:8443
Accept: */*
Cookie: unifises=Dvmdd2hzTpxkf3XGzHcpvNukeEK0Gn6I;csrf_token=mhTIMY9mZpoYgM6GCIw6Kk6dXXxWaRNz
Content-Type: application/json;charset=UTF-8
Content-Length: 98

* upload completely sent off: 98 out of 98 bytes
< HTTP/1.1 401 
< vary: Origin
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
< X-Frame-Options: DENY
< Content-Type: application/json;charset=UTF-8
< Content-Length: 63
< Date: Thu, 27 Feb 2020 23:12:00 GMT
< 
* Connection #0 to host wifi.haciendasanandres.mx left intact

**Comment by nmlpg12** [comment]
* upload completely sent off: 93 out of 93 bytes
< HTTP/1.1[Thu Feb 27 23:28:14.774622 2020] [php7:notice] [pid 778] [client ::1:51062] cURL debug: needed to reconnect to UniFi controller, referer: http://localhost/unifi-voucher-service/index.php
 401 
< vary: Origin
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
< X-Frame-Options: DENY
< Content-Type: application/json;charset=UTF-8
< Content-Length: 63
< Date: Thu, 27 Feb 2020 23:28:13 GMT
< 
* Connection #0 to host wifi.haciendasanandres.mx left intact
* Expire in 0 ms for 6 (transfer 0x634770)
* Expire in 10000 ms for 2 (transfer 0x634770)

**Comment by nmlpg12** [comment]
i no longer have php errors but i still can't get it to work ..

**Comment by nmlpg12** [comment]
Fixed php error and it was due to lowercase in a folder and fixed it ; now the problem 401 error with the controller
Expire in 200 ms for 4 (transfer 0x1a6fd10)
* Connected to wifi.haciendasanandres.mx (149.28.49.108) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=wifi.haciendasanandres.mx
*  start date: Dec 29 22:00:47 2019 GMT
*  expire date: Mar 28 22:00:47 2020 GMT
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> POST /api/s/default/cmd/hotspot HTTP/1.1
Host: wifi.haciendasanandres.mx:8443
Accept: */*
Cookie: unifises=0UhyWGjNbGAMa1lGHOf00sQTp54Ibxd0;csrf_token=sTWMu2ja1t7ykXYJNfMvMW1xD3e7naOU
Content-Type: application/json;charset=UTF-8
Content-Length: 93

* upload completely sent off: 93 out of 93 bytes
< HTTP/1.1 401 
< vary: Origin
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
< X-Frame-Options: DENY
< Content-Type: application/json;charset=UTF-8
< Content-Length: 63
< Date: Fri, 28 Feb 2020 01:04:11 GMT
< 

* Connection #0 to host wifi.haciendasanandres.mx left intact

**Comment by nmlpg12** [comment]
the controller has multiple sites , but the account i assigned to printer has only access to that site specifically do i have to add something extra to make it work

**Comment by nmlpg12** [comment]
rying 149.28.49.108...
* TCP_NODELAY set
* Expire in 200 [Fri Feb 28 01:41:15.680425 2020] [php7:notice] [pid 13659] [client ::1:46638] cURL debug: needed to reconnect to UniFi controller, referer: http://localhost/unifi-voucher-service/index.php
ms for 4 (transfer 0x1a781a8)
* Connected to wifi.haciendasanandres.mx (149.28.49.108) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=wifi.haciendasanandres.mx
*  start date: Dec 29 22:00:47 2019 GMT
*  expire date: Mar 28 22:00:47 2020 GMT
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> POST /api/s/default/cmd/hotspot HTTP/1.1
Host: wifi.haciendasanandres.mx:8443
Accept: */*
Cookie: unifises=VAfhOli9pJdn6G1X4RcoAc0DvGtA3oJv;csrf_token=eFcW2ojDF0KJ36rlLyyoSP93jQ88Xy1c
Content-Type: application/json;charset=UTF-8
Content-Length: 93

* upload completely sent off: 93 out of 93 bytes
< HTTP/1.1 401 
< vary: Origin
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
< X-Frame-Options: DENY
< Content-Type: application/json;charset=UTF-8
< Content-Length: 63
< Date: Fri, 28 Feb 2020 01:41:15 GMT
<

**Comment by nmlpg12** [comment]
ok finally got that fixed the problem was that i needed to add few lines of code 
(add site id) now its generating vouchers
now i need the proper syntax to produce the following code
sudo brother_ql -p usb://04f9:209b -m QL-800 print -l  62 voucher_final.png --red
it has to send the command in that order to work.

shell_exec("sudo brother_ql -p usb://" . $uvs_usbid . " -m " . $uvs_printer . " print -l " . $uvs_labelsize .  " /var/www/html/" . $uvs_folder . "/codeimage/voucher_final.png"). " --red";

**Comment by nmlpg12** [comment]
just to let you know that i finally fixed everything. it prints now  and yea i had to add few lines of code to the config.php stating the siteid (cloud controller hostifi and managing several sites myself) 

and to make the brother ql 800 the solution given was the following 
shell_exec("sudo brother_ql -p usb://" . $uvs_usbid . " -m " . $uvs_printer . " print -l " . $uvs_labelsize . " /var/www/html/" . $uvs_folder . "/codeimage/voucher_final.png". " --red") ;

or manualy set 
hell_exec("sudo brother_ql -p usb://" . $uvs_usbid . "  -m QL-800 print -l 62" ." /var/www/html/" . $uvs_folder . "/codeimage/voucher_final.png". " --red");
