### ISSUE TITLE
SSID does not Print on Voucher with Unifi Controller Version 6.0.45

### ISSUE THREAD

**Issue by bennyboomardy** [PaintSplasher/unifi-voucher-service#12]
Hi  PaintSplash,

Updated to Unifi Controller Version 6.0.45 and had to change the Controller URL in the Config.php file from https://192.168.1.2:8443 to https://192.168.1.2:443 now it has started to print my guest vouchers out again but it is not printing with the SSID on the Voucher can you help me fix this as I use this all day long in my workplace.

also is there any way to remove the download speed and upload speed from the Voucher so it does not print it on the voucher as I do not want to show this to my guests when i give them a voucher.

**Comment by PaintSplasher** [comment]
Hi, the options for own changes and variables are very limited on this version. I'm currently working on v3 which will have a lot of more features and possibilities to change things easily. This new release will also came with a complete web overlay. The reason why your SSID is not printing anymore is duo a change from uniFi and their API-client, which has to be updated.

**Comment by bennyboomardy** [comment]
Ok can you please advise once version 2 comes out

**Comment by PaintSplasher** [comment]
I plan to release everything around June 2021.
