### ISSUE TITLE
Difference between this and the Pro version

### ISSUE THREAD

**Issue by ljacobo** [PaintSplasher/unifi-voucher-service#13]
Hi,

What's the difference between this version and the Pro version that is listed in https://shop.sass-projects.info/?

Thank you!!

**Comment by PaintSplasher** [comment]
Hey,

basically, it is compatible to the new USG/Pro, CLoudKey/2 and all new versions from 6.x.xx up to the current 6.5.xx as a complete rewritten product. 

*	Fully responsive design:Choose your own monitor resolution
*	Auto installscript:No linux knowledge necessary
*	Multiple settings:Up to nine pre-defined tickets
*	Corporate identity:Easy colour & font customize
*	Touch-screen optimized:Integrated numpad and keyboard
*	Different front-pages:Individually or pre-defined tickets
*	Multi-language:Translated in DE, EN, NL, FR, ES, IT, SE

Additional it has a lot of customizations you can do, without any knowledge, multiple printer support, multiple voucher settings and thermopaper support.

Details: https://shop.sass-projects.info/en/shop_uvs3product.php

Maybe if you have a more specific question I can answer yours in more detail.

Best Regards
Thorsten Sass

**Comment by ljacobo** [comment]
Perfect..

Just asking because I see this repo super complete, but I am interested in the Pro version. The price is 29.90 eu + license support every 6 months, right?

Thanks.

**Comment by PaintSplasher** [comment]
This repo is complete and working, but not 100% compatible to the USGs and new unifi versions.

And yes, correct.

**Comment by ljacobo** [comment]
Perfect.!!
