### ISSUE TITLE
Error at the buying website

### ISSUE THREAD

**Issue by ljacobo** [PaintSplasher/unifi-voucher-service#14]
Hi,

I am trying to purchase the PRO version in [](https://shop.sass-projects.info/), but the page stills loading in:

Your payment is now in progress....

But the page doesn't refresh or do anything else.

Can I buy it directly and you send me the purchase order from Paypal?

My paypal is dot com.

**Comment by PaintSplasher** [comment]
I send you a request.

**Comment by ljacobo** [comment]
> I send you a request.

Done.!

**Comment by ljacobo** [comment]
How can I download the software?

**Comment by PaintSplasher** [comment]
You've an email with all information's.
