### ISSUE TITLE
Logos umändern

### ISSUE THREAD

**Issue by philg1234** [PaintSplasher/unifi-voucher-service#6]
Hallo zusammen,

danke im Voraus für das Klasse Projekt. Ich habe es umgesetzt und bin begeistert.
Momentan bin ich daran die Übersetzung auf Deutsch zu machen und würde hierfür gerne die Logos austauschen.

Damit nicht mehr 1 Days Voucher Free dort steht.
Ich habe bereits versucht ein anderes Bild vom gleichen Namen auf den Raspberry Pi zu kopieren, allerdings ohne Erfolg.

Könnten Sie mir verraten, wie ich die Logos ändern kann?

Danke im Voraus.

Grüße Phil

**Comment by philg1234** [comment]
kurzes Edit:

die Bilder werden aktualisiert, es war lediglich der Cache im Browser noch vorhanden.

Eine Frage hätte ich allerdings noch zu der Hintergrundfarbe in dem "index_custom.php".

Wie kann ich diesen von Orange ändern?

**Comment by PaintSplasher** [comment]
Hallo, in der Datei /assets/css/style.min.css sind alle Farben hinterlegt. Suchen sie dort die gewünschte Farbe die geändert werden soll. Orange wäre zum Beispiel: "#f0ad4e".

**Comment by philg1234** [comment]
@PaintSplasher 
danke dir für die schnelle Antwort. Dies werde ich mir heute anschauen.

Wenn ich schon den Entwickler an der Hand habe ;-), wenn ich in der index_custom.php weiter Dropdown Felder einsetzen will, z.b. weitere Bandbreiten, reicht dies aus einfach im Script weitere aufzulisten?

Oder sind fixe Variablen im Script vorhanden, so dass ich nur diese nutzen kann?

Danke im Voraus und nochmals auch für das Klasse Projekt *thumsup*

**Comment by philg1234** [comment]
Edit:

ich habe nun die Farbe und die Optionen im Dropdown getestet. Es funktioniert alles super und reibungslos.

Danke für alles.
