### ISSUE TITLE
Voucher Printing

### ISSUE THREAD

**Issue by JK7398** [PaintSplasher/unifi-voucher-service#7]
Hey, is there any possybility to print more than one Voucher?

Mfg

**Comment by philg1234** [comment]
Hi,

steht alles im Github beschrieben, dass momentan nur einer ausgedruckt werden kann.
Du kannst aber mehrere Geräte auf einen Voucher zulassen.

Grüße Phil

**Comment by PaintSplasher** [comment]
This is currently not possible.
