### ISSUE TITLE
Probleme beim Druck 

### ISSUE THREAD

**Issue by philg1234** [PaintSplasher/unifi-voucher-service#9]
Hi,

ich habe ein Problem beim Druck der Vouchers.
Wenn ich den Testdruck absetzte:

sudo brother_ql -p usb://04f9:2042 -m QL-700 print -l 62x29 test-print.png

Funktioniert alles perfekt.

Auch wenn ich über die Website ein beliebigen Text ausdrucke funktioniert alles Problemlos.

Wenn ich allerdings die Buttons drücke wird zwar "successfull" angezeigt, allerdings kommt kein Voucher raus.

Danke im Voraus.

Grüße Phil

**Comment by james-lasersoft** [comment]
I just had this same issue and it was caused by permissions and ownership on the /var/www/html and the codeimage directory.
